-- 1. Tabell för profiler (kopplad till inloggning)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  role TEXT DEFAULT 'customer' -- Kan vara 'admin' eller 'customer'
);

-- 2. Tabell för jobb
CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  customer_id UUID REFERENCES auth.users NOT NULL
);

-- 3. Tabell för kandidater
CREATE TABLE candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  linkedin_url TEXT,
  status TEXT DEFAULT 'new', -- 'new', 'interview', 'rejected', 'hired'
  job_id BIGINT REFERENCES jobs ON DELETE CASCADE,
  customer_id UUID REFERENCES auth.users NOT NULL
);